#%RAML 0.8
title: Steroids Data
mediaType: application/json
baseUri: https://rest-api.appgyver.com/v1/

traits:
  - securedBySteroidsApiKey:
      headers:
        steroidsApiKey:
          type: string
          example: exampleapikey
          default: a254e2f5a3ae4de710212be8ae7f0dab008530aa86a5ed12c73fe653437d32df
        steroidsAppId:
          type: integer
          example: 1234
          default: 39720

schemas:
  - home_collection: '{"$schema":"http://json-schema.org/schema","title":"home collection","type":"object","properties":{"results":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical home representation","properties":{"ad":{"type":"string"},"ba":{"type":"string"},"bd":{"type":"integer"},"createdAt":{"type":"string"},"ft":{"type":"integer"},"ml":{"type":"string"},"objectId":{"type":"string"},"pr":{"type":"integer"},"updatedAt":{"type":"string"},"yr":{"type":"integer"}},"required":[]}}}}'
  - home_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical home representation","properties":{"ad":{"type":"string"},"ba":{"type":"string"},"bd":{"type":"integer"},"createdAt":{"type":"string"},"ft":{"type":"integer"},"ml":{"type":"string"},"objectId":{"type":"string"},"pr":{"type":"integer"},"updatedAt":{"type":"string"},"yr":{"type":"integer"}},"required":[]}'

resourceTypes:
  - parse_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "results"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - parse_member:
      usage: This resourceType should be used for any parse item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:


/home:
  description: |
    {
      "resourceName": "home",
      "identifierKey": "objectId"
    }
  type: parse_collection
  /{id}:
    type: parse_member


